baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "jieqi's archive"
theme = 'hugo-bearblog'

[markup]
  [markup.highlight]
    style = "catppuccin-latte"   # Or any Chroma-supported theme
    noClasses = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
