export const SITE = {
  website: "https://jieqiboh.me/",
  author: "jieqiboh",
  profile: "https://github.com/jieqiboh",
  desc: "jieqi's archive",
  title: "jieqi's archive",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/jieqiboh/jieqiboh.github.io/edit/main/src/data/blog/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Singapore",
} as const;
